#!/bin/sh

NETNS="$1"

ADDR=$(awk -F\" '/local_gn_addr/ {print $2}' /var/run/itseml/env1/itsnet.conf)

echo $ADDR

if [ ${ADDR} = "0:0:0:1" ]; then
    ADDR=$(ip netns exec ${NETNS} ip -o l show eth0 | \
       sed -e 's/^.*ether //' -e 's/://g' -e 's/^/0000/' | \
       awk '{print $1;}' | sed -e 's/.\{4\}/&:/g' -e 's/:$//')

    sed -i -e "s/0:0:0:1/$ADDR/" \
       /var/run/itseml/${NETNS}/itsnet.conf
else
    MAC_ADDR=$(echo ${ADDR} | cut -d: -f2-4 | sed -e 's/://g' -e 's/.\{2\}/&:/g' -e 's/:$//')
echo $MAC_ADDR
    ip netns exec ${NETNS} ip l set dev eth0 down
    ip netns exec ${NETNS} ip l set dev eth0 address ${MAC_ADDR}
    ip netns exec ${NETNS} ip l set dev eth0 up
fi

sed -i -e "s,^#SAPSocket.*,SAPSocket = /var/run/itseml/${NETNS}/GN_SAP.sock," \
       /var/run/itseml/${NETNS}/itsnet.conf
